# Autogenerated by devscripts/update-version.py

__version__ = '2026.01.04.062910'

RELEASE_GIT_HEAD = '5a5ae94a1cf308ecff1ab954e9371d37b41ed022'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Rei3100/yt-dlp'

ORIGIN = 'Rei3100/yt-dlp'

_pkg_version = '2026.01.04.062910'
