# Autogenerated by devscripts/update-version.py

__version__ = '2025.11.07.090125'

RELEASE_GIT_HEAD = '78654aa1075184268a32dc569fa09cde43a11356'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Rei3100/yt-dlp'

ORIGIN = 'Rei3100/yt-dlp'

_pkg_version = '2025.11.07.090125'
