# Autogenerated by devscripts/update-version.py

__version__ = '2025.12.22.051717'

RELEASE_GIT_HEAD = '6d67e510bff07dd08af222172963490f13a09e98'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Rei3100/yt-dlp'

ORIGIN = 'Rei3100/yt-dlp'

_pkg_version = '2025.12.22.051717'
